FetchService créé close #5
jpheos/scrapper pull request #9
Opened 2020-07-18 10:08 UTC by inicolas69

Fetch service créé :
* Petite modif dans l'engine, pour qu'il return les infos et pas seulement les affiche
* Fetch service à améliorer au niveau des infos dans les items
* Petit prob au niveau des images, a voir d'ou cela vient

Seeds créé :
* Le seed crée un user s'il n'y en a pas, lui crée une area et un JsonEntry fonctionnel

2020-07-19 21:10 UTC, jpheos requested changes
Deux micro changement.
Bien joué 👍

2020-07-19 21:10 UTC, jpheos commented on app/services/fetch_items_from_json_entry.rb
> +require_relative "../../lib/scrapper/engine.rb"
changer par `require 'scrapper/engine'`

2020-07-19 21:10 UTC, jpheos commented on app/services/fetch_items_from_json_entry.rb
> +        ad2.save!
de ce que je comprend [ici](https://apidock.com/rails/v6.0.0/ActiveRecord/Relation/find_or_create_by) il n'y a pas besoin de faire un `save!`

2020-07-19 21:15 UTC, inicolas69 commented on app/services/fetch_items_from_json_entry.rb
> +require_relative "../../lib/scrapper/engine.rb"
Ah d'accord, je ne savais pas que le require allait chercher tout seul dans le dossier lib 👌🏻

2020-07-19 21:18 UTC, inicolas69 commented on app/services/fetch_items_from_json_entry.rb
> +        ad2.save!
Dacc je note !

2020-07-20 20:27 UTC, jpheos approved these changes

2020-07-20 20:27 UTC, merged